WITH BIKE AS (
    select
    TRIPDURATION,
    START_TIME,
    STOP_TIME,
    START_STATION_ID,
    START_STATION_NAME,
    START_STATION_LAT,
    START_STATION_LONG,
    END_STATION_ID,
    END_STATION_NAME,
    END_STATION_LAT,
    END_STATION_LONG,
    BIKE_ID,
    USER_TYPE,
    BIRTH_YEAR,
    GENDER
    from {{ source('DEMO', 'BIKE_2018') }}
)

select * from BIKE