WITH TRIPS AS (

    select 
    RIDE_ID,
    RIDEABLE_TYPE,
    DATE(STARTED_AT) AS TRIP_DATE,
    START_STATION_ID,
    END_STATION__ID,
    MEMBER_CASUAL,
    TIMESTAMPDIFF(SECOND, STARTED_AT, ENDED_AT) AS TRIP_DURATION
    FROM
    {{ source('DEMO', 'BIKE_2023') }}
)

SELECT * FROM TRIPS